# Copyright (c) 2020, NVIDIA CORPORATION.

{% set rapids_version = environ.get('RAPIDS_VER', '0.0.0') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA_VER', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in
#   `ci/cpu/build-env.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml`
#   to set these versions
###

package:
  name: rapids-notebook-env
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CUDA_VERSION
    - RAPIDS_VER
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - bokeh {{ bokeh_version }}
    - colorcet
    - conda-forge::blas
    - cudatoolkit ={{ cuda_version }}.*
    - cupy {{ cupy_version }}
    - cython {{ cython_version }}
    - dask-labextension
    - dask-ml
    - datashader {{ datashader_version }}
    - fa2
    - filterpy
    - holoviews
    - ipython {{ ipython_version }}
    - ipywidgets
    - jupyter-server-proxy
    - jupyterlab {{ jupyterlab_version }}
    - jupyterlab-nvdashboard
    - jupyter-packaging {{ jupyter_packaging_version }}
    - jupyterlab_widgets
    - matplotlib-base
    - networkx {{ networkx_version }}
    - nodejs {{ nodejs_version }}
    - openslide
    - pytest
    - s3fs {{ s3fs_version }}
    - scikit-image {{ scikit_image_version }}
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - seaborn
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Notebook Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing notebook dependencies and tools needed to run RAPIDS notebooks.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
