# Copyright (c) 2020-2023, NVIDIA CORPORATION.

{% set rapids_version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
###

package:
  name: rapids-notebook-env
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
  run:
    - bokeh {{ bokeh_version }}
    - colorcet
    - conda-forge::blas
    - cudatoolkit ={{ cuda_major }}.*
    - cupy {{ cupy_version }}
    - cython {{ cython_version }}
    - dask {{ dask_version }}
    - dask-core {{ dask_version }}
    - dask-labextension
    - dask-ml
    - datashader {{ datashader_version }}
    - distributed {{ distributed_version }}
    - filterpy
    - holoviews
    - ipython {{ ipython_version }}
    - ipykernel {{ ipykernel_version }}
    - ipywidgets
    - jupyter-server-proxy
    - jupyterlab {{ jupyterlab_version }}
    - jupyterlab-favorites
    - jupyter-packaging {{ jupyter_packaging_version }}
    - jupyterlab_widgets
    - matplotlib-base
    - networkx {{ networkx_version }}
    - nodejs {{ nodejs_version }}
    - openslide
    - pytest
    - pillow {{ pillow_version }}
    - s3fs {{ s3fs_version }}
    - scikit-image {{ scikit_image_version }}
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - seaborn
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Notebook Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing notebook dependencies and tools needed to run RAPIDS notebooks.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
