# Copyright (c) 2020, NVIDIA CORPORATION.

{% set rapids_version = environ.get('RAPIDS_VER', '0.0.0') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set py_version = environ.get('CONDA_PY', 36) %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in
#   `ci/cpu/build-env.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml`
#   to set these versions
###

package:
  name: rapids-doc-env
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - RAPIDS_VER
    - VERSION_SUFFIX

requirements:
  host:
    - python
    - pip
  run:
    - beautifulsoup4
    - doxygen {{ doxygen_version }}
    - jupyter_sphinx
    - markdown
    - nbsphinx
    - numpydoc
    - pandoc {{ pandoc_version }}
    - recommonmark
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-websupport
    - sphinx-click
    - sphinx-copybutton
    - sphinx-markdown-tables

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Documentation Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing documentation build dependencies and tools needed to build RAPIDS docs.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
