# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  rapids_version: ${{ env.get("GIT_DESCRIBE_TAG", default="0.0.0.dev") | replace("v", "")}}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: rapids-xgboost
  version: ${{ rapids_version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}

requirements:
  host:
    - cuda-version =${{ cuda_version }}
    - pip
    - python =${{ py_version }}
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - nccl ${{ nccl_version }}
    - python
    - libxgboost ${{ xgboost_version }} rapidsai_h*
    - xgboost ${{ xgboost_version }} rapidsai_py*
  ignore_run_exports:
    by_name:
      - python_abi

about:
  homepage: https://rapids.ai
  license: LicenseRef-Custom
  license_file: LICENSE
  summary: RAPIDS Suite - Open GPU Data Science
