# Copyright (c) 2020, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set rapids_version = environ.get('RAPIDS_VER', '0.0.0') }
{% set minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

### 
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in 
#   `ci/cpu/build-env.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml` 
#   to set these versions
###

package:
  name: rapids-build-env
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CUDA_VERSION
    - RAPIDS_VER
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - arrow-cpp {{ arrow_version }}
    - arrow-cpp-proc * cuda
    - async_generator
    - autoconf
    - automake
    - black
    - conda-forge::blas{{ blas_version }}
    - boost
    - boost-cpp {{ boost_cpp_version }}
    - boto3
    - conda-forge::clang {{ clang_version }}
    - conda-forge::clang-tools {{ clang_version }}
    - cmake {{ cmake_version }}
    - cmake_setuptools {{ cmake_setuptools_version }}
    - conda {{ conda_version }}
    - conda-build {{ conda_build_version }}
    - conda-verify {{ conda_verify_version }}
    - cudatoolkit ={{ cuda_version }}.*
    - cupy {{ cupy_version }}
    - cython {{ cython_version }}
    - dask {{ dask_version }}
    - datashader {{ datashader_version }}
    - distributed {{ distributed_version }}
    - dlpack {{ dlpack_version }}
    - double-conversion {{ double_conversion_version }}
    - fastavro {{ fastavro_version }}
    - feather-format
    - flake8
    - flatbuffers {{ flatbuffers_version }}
    - fsspec {{ fsspec_version }}
    - gcsfs
    - gdal {{ gdal_version }}
    - geopandas {{ geopandas_version }}
    - git
    - graphviz
    - httpretty
    - hypothesis
    - isort
    - lapack
    - libcumlprims ={{ minor_version }}.*
    - libcypher-parser
    - libgcc-ng {{ build_stack_version }}
    - libgfortran-ng {{ build_stack_version }}
    - libhwloc
    - liblapack
    - librdkafka {{ librdkafka_version }}
    - libstdcxx-ng {{ build_stack_version }}
    - libtool
    - libwebp
    - lightgbm
    - make
    - moto
    - nccl {{ nccl_version }}
    - networkx {{ networkx_version }}
    - numba {{ numba_version }}
    - numpy {{ numpy_version }}
    - pandas {{ pandas_version }}
    - panel {{ panel_version }}
    - pkg-config
    - protobuf {{ protobuf_version }}
    - psutil
    - pyarrow {{ arrow_version }}
    - pynvml
    - pyppeteer
    - pyproj {{ pyproj_version }}
    - pytest
    - pytest-asyncio
    - pytest-benchmark
    - pytest-cov
    - pytest-timeout
    - python
    - python-louvain
    - rapidjson {{ rapidjson_version }}
    - ripgrep
    - s3fs
    - setuptools
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - shellcheck
    - spdlog {{ spdlog_version }}
    - statsmodels
    - streamz
    - twine
    - ucx-py ={{ minor_version }}.*
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Build Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing build dependencies and tools needed to build all RAPIDS libraries.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
