# Copyright (c) 2020-2023, NVIDIA CORPORATION.

{% set rapids_version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
###

package:
  name: rapids-build-env
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
  run:
    - asvdb
    - autoconf
    - automake
    - benchmark {{ benchmark_version }}
    - black {{ black_version }}
    - conda-forge::blas
    - boost
    - boost-cpp {{ boost_cpp_version }}
    - boto3
    - cachetools
    - conda-forge::clang {{ clang_version }} # [x86_64]
    - conda-forge::clang-tools {{ clang_version }} # [x86_64]
    - cmake {{ cmake_version }}
    - cmakelang {{ cmakelang_version }}
    - cmake_setuptools {{ cmake_setuptools_version }}
    - conda {{ conda_version }}
    - conda-build {{ conda_build_version }}
    - conda-verify {{ conda_verify_version }}
    - cubinlinker  # CUDA enhanced compat.
    - cuda-python {{ cuda_python_version }}
    - cudatoolkit ={{ cuda_major }}.*
    - cupy {{ cupy_version }}
    - c-compiler
    - cxx-compiler
    - gcc_impl_{{ target_platform }}  {{ gcc_version }}
    - cython {{ cython_version }}
    - dask {{ dask_version }}
    - dask-core {{ dask_version }}
    - dask-ml
    - datashader {{ datashader_version }}
    - distributed {{ distributed_version }}
    - dlpack {{ dlpack_version }}
    - double-conversion {{ double_conversion_version }}
    - faiss-proc=*=cuda
    - libfaiss {{ faiss_version }}
    - fastavro {{ fastavro_version }}
    - feather-format
    - flake8 {{ flake8_version }}
    - fmt {{ fmt_version }}
    - fsspec {{ fsspec_version }}
    - gcsfs {{ gcsfs_version }}
    - geopandas {{ geopandas_version }}
    - git
    - gmock {{ gmock_version }}
    - graphviz
    - gtest {{ gtest_version }}
    - h5py
    - hdbscan
    - holoviews {{ holoviews_version }}
    - httpretty
    - hypothesis
    - isort {{ isort_version }}
    - lapack
    - libarrow {{ arrow_version }}
    - libcypher-parser
    - liblapack
    - librdkafka {{ librdkafka_version }}
    - libtool
    - libwebp
    - lightgbm
    - make
    - mimesis {{ mimesis_version }}
    - mock
    - moto {{ moto_version }}
    - mypy {{ mypy_version }}
    - nccl {{ nccl_version }}
    - networkx {{ networkx_version }}
    - ninja
    - nltk
    - numba {{ numba_version }}
    - numpy {{ numpy_version }}
    - nvtx {{ nvtx_version }}
    - openslide
    - packaging
    - pandas {{ pandas_version }}
    - panel {{ panel_version }}
    - pillow {{ pillow_version }}
    - pip
    - pkg-config
    - pre-commit
    - protobuf {{ protobuf_version }}
    - psutil
    - ptxcompiler  # CUDA enhanced compat. See https://github.com/rapidsai/ptxcompiler
    - pyarrow {{ arrow_version }}
    - pydeck {{ pydeck_version }}
    - pydocstyle {{ pydocstyle_version }}
    - pynvml
    - pyorc
    - pyppeteer {{ pyppeteer_version }}
    - pyproj {{ pyproj_version }}
    - pytest
    - pytest-asyncio {{ pytest_asyncio_version }}
    - pytest-benchmark
    - pytest-cases
    - pytest-cov
    - pytest-timeout
    - pytest-xdist
    - python
    - python-confluent-kafka {{ python_confluent_kafka_version }}
    - python-louvain
    - python-snappy
    - rapidjson {{ rapidjson_version }}
    - ripgrep
    - s3fs {{ s3fs_version }}
    - setuptools {{ setuptools_version }}
    - scikit-build {{ scikit_build_version }}
    - scikit-image {{ scikit_image_version }}
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - shellcheck
    - spdlog {{ spdlog_version }}
    - statsmodels
    - streamz
    - sysroot_{{ target_platform }} {{ sysroot_version }}
    - thriftpy2
    - tomli  # [py<311]
    - transformers {{ transformers_version }}
    - treelite {{ treelite_version }}
    - twine
    - types-cachetools
    - typing_extensions
    - conda-forge::ucx-proc=*=gpu
    - conda-forge::ucx {{ ucx_version }}
    - umap-learn
    - versioneer {{ versioneer_version }}
    - werkzeug {{ werkzeug_version }} # Temporary transient dependency pinning to avoid URL-LIB3 + moto timeouts

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Build Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing build dependencies and tools needed to build all RAPIDS libraries.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
