# Copyright (c) 2020, NVIDIA CORPORATION.

{% set rapids_version = environ.get('RAPIDS_VER', '0.0.0') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA_VER', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in
#   `ci/cpu/build-env.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml`
#   to set these versions
###

package:
  name: rapids-build-env
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CUDA_VERSION
    - RAPIDS_VER
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - arrow-cpp {{ arrow_version }}
    - arrow-cpp-proc * cuda
    - asvdb
    - autoconf
    - automake
    - benchmark {{ benchmark_version }}
    - black {{ black_version }}
    - conda-forge::blas
    - boost
    - boost-cpp {{ boost_cpp_version }}
    - boto3
    - cachetools
    - conda-forge::clang {{ clang_version }}
    - conda-forge::clang-tools {{ clang_version }}
    - cmake {{ cmake_version }}
    - cmake-format {{ cmake_format_version }}
    - cmake_setuptools {{ cmake_setuptools_version }}
    - conda {{ conda_version }}
    - conda-build {{ conda_build_version }}
    - conda-verify {{ conda_verify_version }}
    - cudatoolkit ={{ cuda_version }}.*
    - cupy {{ cupy_version }}
    - cython {{ cython_version }}
    - dask {{ dask_version }}
    - dask-ml
    - datashader {{ datashader_version }}
    - distributed {{ distributed_version }}
    - dlpack {{ dlpack_version }}
    - double-conversion {{ double_conversion_version }}
    - faiss-proc=*=cuda
    - libfaiss {{ faiss_version }}
    - fastavro {{ fastavro_version }}
    - feather-format
    - flake8 {{ flake8_version }}
    - flatbuffers {{ flatbuffers_version }}
    - fsspec {{ fsspec_version }}
    - gcsfs {{ gcsfs_version }}
    - gdal {{ gdal_version }}
    - geopandas {{ geopandas_version }}
    - git
    - gmock {{ gmock_version }}
    - graphviz
    - gtest {{ gtest_version }}
    - httpretty
    - hypothesis
    - isort {{ isort_version }}
    - lapack
    - libcypher-parser
    - libgcc-ng {{ build_stack_version }}
    - libgfortran-ng {{ build_stack_version }}
    - libhwloc
    - liblapack
    - librdkafka {{ librdkafka_version }}
    - libstdcxx-ng {{ build_stack_version }}
    - libtool
    - libwebp
    - lightgbm
    - make
    - mimesis
    - moto {{ moto_version }}
    - mypy {{ mypy_version }}
    - nccl {{ nccl_version }}
    - networkx {{ networkx_version }}
    - ninja
    - nltk
    - numba {{ numba_version }}
    - numpy {{ numpy_version }}
    - nvtx {{ nvtx_version }}
    - openslide
    - packaging
    - pandas {{ pandas_version }}
    - panel {{ panel_version }}
    - pickle5  # [py<38]
    - pkg-config
    - protobuf {{ protobuf_version }}
    - psutil
    - pyarrow {{ arrow_version }}
    - pydeck {{ pydeck_version }}
    - pydocstyle {{ pydocstyle_version }}
    - pynvml
    - pyorc
    - pyppeteer {{ pyppeteer_version }}
    - pyproj {{ pyproj_version }}
    - pytest
    - pytest-asyncio {{ pytest_asyncio_version }}
    - pytest-benchmark
    - pytest-cov
    - pytest-timeout
    - pytest-xdist
    - python
    - python-confluent-kafka {{ python_confluent_kafka_version }}
    - python-louvain
    - rapidjson {{ rapidjson_version }}
    - ripgrep
    - s3fs {{ s3fs_version }}
    - setuptools
    - scikit-image {{ scikit_image_version }}
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - shellcheck
    - spdlog {{ spdlog_version }}
    - statsmodels
    - streamz
    - transformers
    - treelite {{ treelite_version }}
    - twine
    - typing_extensions
    - ucx-proc=*=gpu
    - ucx
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'RAPIDS Build Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing build dependencies and tools needed to build all RAPIDS libraries.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
