# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set rapids_version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set major_minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
###

package:
  name: rapids
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
    - cuda-version ={{ cuda_version }}
  run:
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cupy {{ cupy_version }}
    - nccl {{ nccl_version }}
    - numba {{ numba_version }}
    - numpy {{ numpy_version }}
    - nvtx {{ nvtx_version }}
    - python
    # TODO: remove all the floors on specific nightly versions once RAPIDS supports 'fmt>11' and 'spdlog>14'
    - cudf ={{ major_minor_version }}.*,>=24.10.00a320
    - cuvs ={{ major_minor_version }}.*,>=24.10.00a60
    - cugraph ={{ major_minor_version }}.*,>=24.10.00a74
    - nx-cugraph ={{ major_minor_version }}.*,>=24.10.00a74
    - cuml ={{ major_minor_version }}.*,>=24.10.00a55
    - cucim ={{ major_minor_version }}.*,>=24.10.00a17
    - cuspatial ={{ major_minor_version }}.*,>=24.10.00a41
    - cuproj ={{ major_minor_version }}.*,>=24.10.00a41
    - custreamz ={{ major_minor_version }}.*,>=24.10.00a320
    - cuxfilter ={{ major_minor_version }}.*,>=24.10.00a19
    - dask-cuda ={{ major_minor_version }}.*,>=24.10.00a19
    - rapids-xgboost ={{ major_minor_version }}.*
    - rmm ={{ major_minor_version }}.*,>=24.10.00a38
    - pylibcugraph ={{ major_minor_version }}.*,>=24.10.00a74
    - libcugraph_etl ={{ major_minor_version }}.*,>=24.10.00a74
    {% if cuda_major == "11" %}
    - ptxcompiler  # CUDA enhanced compat. See https://github.com/rapidsai/ptxcompiler
    {% endif %}
    - conda-forge::ucx {{ ucx_version }}
    # TODO: remove pins on pyogrio and tiledb once cuspatial supports 'fmt>11' and 'spdlog>14'
    # ref:
    #   * https://github.com/rapidsai/build-planning/issues/56
    #   * https://github.com/rapidsai/cuspatial/pull/1453#issuecomment-2335527542
    - pyogrio <0.8
    - tiledb <2.19

test:
  requires:
    - cuda-version ={{ cuda_version }}
  commands:
    - exit 0

about:
  home: https://rapids.ai/
  license: Custom
  license_file: conda/recipes/rapids/LICENSE
  summary: 'RAPIDS Suite - Open GPU Data Science'
  description: |
    Meta-package for the RAPIDS suite of software libraries. RAPIDS gives you the freedom to execute end-to-end data science
    and analytics pipelines entirely on GPUs. It relies on NVIDIA® CUDA® primitives for low-level compute optimization,
    but exposes that GPU parallelism and high-bandwidth memory speed through user-friendly Python interfaces.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
