# Copyright (c) 2019, NVIDIA CORPORATION.

{% set rapids_version = environ.get('RAPIDS_VER', '0.0.0') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = rapids_version.split('.')[0] + '.' + rapids_version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA_VER', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}
{% set cuda_major=cuda_version.split('.')[0] %}

###
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in
#   `ci/cpu/build-meta.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml`
#   to set these versions
###

package:
  name: rapids
  version: {{ rapids_version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CUDA_VERSION
    - RAPIDS_VER
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - cuda-python {{ cuda_python_version }}
    - cudatoolkit ={{ cuda_major }}.*
    - cupy {{ cupy_version }}
    - nccl {{ nccl_version }}
    - networkx {{ networkx_version }}
    - numba {{ numba_version }}
    - numpy {{ numpy_version }}
    - nvtx {{ nvtx_version }}
    - pickle5  # [py<38]
    - python
    - setuptools {{ setuptools_version }}
    - cudf ={{ minor_version }}.*
    - cugraph ={{ minor_version }}.*
    - cuml ={{ minor_version }}.*
    - cucim ={{ minor_version }}.*
    - cusignal ={{ minor_version }}.*
    - cuspatial ={{ minor_version }}.*
    - custreamz ={{ minor_version }}.*
    - cuxfilter ={{ minor_version }}.*
    - dask-cuda ={{ minor_version }}.*
    - rapids-xgboost ={{ minor_version }}.*
    - rmm ={{ minor_version }}.*
    - pylibcugraph ={{ minor_version }}.*
    - libcugraph_etl ={{ minor_version }}.*
    - ptxcompiler  # [linux64]  # CUDA enhanced compat. See https://github.com/rapidsai/ptxcompiler

test:              # [linux64]
  imports:         # [linux64]
    - cucim        # [linux64]
    - cudf         # [linux64]
    - cudf_kafka   # [linux64]
    - cugraph      # [linux64]
    - cuml         # [lunux64]
    - cusignal     # [linux64]
    - cuspatial    # [linux64]
    - custreamz    # [linux64]
    - cuxfilter    # [linux64]
    - dask_cuda    # [linux64]
    - dask_cudf    # [linux64]
    - pylibcugraph # [linux64]
    - rmm          # [linux64]

about:
  home: http://rapids.ai/
  license: Custom
  license_file: conda/recipes/rapids/LICENSE
  summary: 'RAPIDS Suite - Open GPU Data Science'
  description: |
    Meta-package for the RAPIDS suite of software libraries. RAPIDS gives you the freedom to execute end-to-end data science
    and analytics pipelines entirely on GPUs. It relies on NVIDIA® CUDA® primitives for low-level compute optimization,
    but exposes that GPU parallelism and high-bandwidth memory speed through user-friendly Python interfaces.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
